### ISSUE TITLE
Logger revisions tracking

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#49]
- [x] Decide on pair of format styles -- dev and user: https://github.com/epigen/looper/issues/40#issue-208183000; https://github.com/epigen/looper/pull/36#issuecomment-280396222
- [x] Invert verbosity nomenclature on user side while preserving builtin `logging` names for devs
- [x] Cleanup message length (time, logger name, etc.): https://github.com/epigen/looper/issues/40#issuecomment-280412113
- [x] Squelch message duplication (handlers), eliminating unformatted messages: https://github.com/epigen/looper/issues/40#issuecomment-280409898
- [x] Output to out not err by default

**Comment by nsheff** [comment]
* [ ] Have logger output all to stdout instead of stderr (maybe) ? Thoughts?

**Comment by vreuter** [comment]
:ok_hand:

**Comment by nsheff** [comment]
for pair of format styles; can we have a hidden command-line argument (eg `--devmode`) that flips the format style (and could also increase verbosity)? by hidden I mean it doesn't show up in usage, so the user doesn't get annoyed by too many options. not sure if that's a good idea, just a thought.

**Comment by vreuter** [comment]
`--devmode` has been implemented as `--debug`
